# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: pypy3
      env: TOX_ENV=pypy3
    - python: 3.8
      env: TOX_ENV=py38
    - python: 3.6
      env: TOX_ENV=flake8

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
