site_name: pytest-qgis
site_description: A pytest plugin for testing QGIS python plugins
site_author: Joona Laine

theme: readthedocs

repo_url: https://github.com/GispoCoding/pytest-qgis

pages:
- Home: index.md
